name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  # Don't run tests on tag pushes (handled by build workflow)
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.x'

jobs:
  #######################################################################
  # Multi-platform Tests with Matrix
  #######################################################################
  test:
    if: "!startsWith(github.ref, 'refs/tags/')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: Linux
          - os: macos-latest
            platform: macOS
          - os: windows-latest
            platform: Windows
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Run tests
        run: dotnet cake --target=test --configuration=release
        continue-on-error: true

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: ${{ matrix.platform }} Test Results
          path: 'artifacts/*.trx'
          reporter: dotnet-trx
          fail-on-error: true

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.platform }}
          path: artifacts/*.trx
          retention-days: 30
