name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  # Don't run tests on tag pushes (handled by build workflow)
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.x'

jobs:
  test:
    if: "!startsWith(github.ref, 'refs/tags/')"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: Linux
          - os: macos-latest
            platform: macOS
          - os: windows-latest
            platform: Windows
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: preview

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Run tests
        run: dotnet cake --target=test --configuration=release
